### ISSUE TITLE
Using generator: getVtimezoneComponent

### ISSUE THREAD

**Issue by jetstudio** [sebbo2002/ical-generator#312]
I am getting errors when trying to generate ical like below 
```typescript
import * as icaltz from '@touch4it/ical-timezones';
import ical, { ICalCalendar } from 'ical-generator';

const cal = new ICalCalendar();
cal.timezone({
    name: moment.tz.guess(), 
    generator: icaltz.getVtimezoneComponent
});
console.log('ical-generator lib output', cal.toString())
```
```
Error: ./node_modules/path/path.js
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: ENOENT: no such file or directory, open 'D:\projects\sae-ng-global\node_modules\path\path.js'
```
This is compilation error from vscode and I am able to get rid of it by running `npm i -D path`. But the second error is a runtime error from browser where it complains 
```
ERROR Error: Uncaught (in promise): ReferenceError: process is not defined
ReferenceError: process is not defined
```
I am not sure how to overcome this, it works fine if I remove `generator: icaltz.getVtimezoneComponent`, but the output result will not have `VTIMEZONE`. I am working on an Angular application v11.5.2. I have installed all the listed dependencies

**Comment by sebbo2002** [comment]
@jetstudio I have only rudimentarily skimmed the code of ical-timezones, but as far as I can see, this module is not designed for use in browsers. Modules like `fs` or `path` are used here that do not exist in the browser. You would therefore either have to move this part to the backend or make sure that you get your hands on a generator that also works in the frontend (be it through a fork, implement it yourself, etc.).

I am closing this issue as it only marginally concerns ical-generator. Feel free to create a new one if you have further questions.

**Comment by jetstudio** [comment]
Thanks for your quick response, moving the ical generation logic to backend sounds like a good move. Thanks for the idea.
