### ISSUE TITLE
Build Failure: "TypeError: ical is not a function"

### ISSUE THREAD

**Issue by Sean12697** [sebbo2002/ical-generator#247]
@dependabot-preview opened a PR (https://github.com/inevitable-team/compiled-mcr-events/pull/81) to Bump ical-generator from 1.15.1 to 2.0.0 and generated the following [Deploy Log](https://app.netlify.com/sites/manchester-tech-events/deploys/608a57ad039fc500078df2df) in a triggered Netlify Build Step.

```bash
7:53:31 AM: ────────────────────────────────────────────────────────────────
7:53:31 AM:   1. Build command from Netlify app                             
7:53:31 AM: ────────────────────────────────────────────────────────────────
7:53:31 AM: ​
7:53:31 AM: $ node script
7:53:31 AM: /opt/build/repo/script.js:15
7:53:31 AM: let cal = ical({domain: 'https://events.compiledmcr.com/', name: 'CompiledMCR Events (Manchester Tech Meetups)'});
7:53:31 AM:           ^
7:53:31 AM: TypeError: ical is not a function
7:53:31 AM:     at Object.<anonymous> (/opt/build/repo/script.js:15:11)
7:53:31 AM:     at Module._compile (internal/modules/cjs/loader.js:778:30)
7:53:31 AM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
7:53:31 AM:     at Module.load (internal/modules/cjs/loader.js:653:32)
7:53:31 AM:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
7:53:31 AM:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
7:53:31 AM:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
7:53:31 AM:     at startup (internal/bootstrap/node.js:283:19)
7:53:31 AM:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
7:53:31 AM: ​
7:53:31 AM: ────────────────────────────────────────────────────────────────
7:53:31 AM:   "build.command" failed                                        
7:53:31 AM: ────────────────────────────────────────────────────────────────
```

The code that has caused this issue, which still works on ical-generator@1.15.1 / ical-generator@1.15.4, is as below.

https://github.com/inevitable-team/compiled-mcr-events/blob/77beed9d23ea947a4bf3599948acac5714a3fe5b/script.js#L1-L15

**Comment by sebbo2002** [comment]
Damn. I completely forgot to adjust the documentation regarding the new imports. Please adapt your code as follows, that should work. I will update the documentation as soon as I have time. 

```js
let ical = require('ical-generator').default; // use default export here
let cal = ical({domain: 'https://events.compiledmcr.com/', name: 'CompiledMCR Events (Manchester Tech Meetups)'});

// cal.toString();
```

Thank you for bringing this to my attention. ❤️

**Comment by Sean12697** [comment]
No worries @sebbo2002, the default export implementation has worked and I'm happy to close this issue, unless you want to keep it open until you update the documentation?

**Comment by sebbo2002** [comment]
I would suggest leaving it open, I will close the issue when the documentation has been reworked. Thank you.
